name: integration-tests

on: [push, pull_request]

jobs:
  XXX:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
        poetry-version: ["1.2.1"]
    steps:
      - uses: actions/checkout@v2
      - name: setup-jmeter
        run: |
          sudo apt-get update
          sudo apt install curl -y
          sudo apt install -y default-jdk
          sudo curl -O https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.5.tgz 
          sudo tar -xvf apache-jmeter-5.5.tgz

      - name: run-jmeter-tests
        run: |
          $GITHUB_WORKSPACE/apache-jmeter-5.5/bin/./jmeter.sh -n -t tests/loadtests/watchonly-satspay-tipjar.jmx -l watchonly-satspay-tipjar-result.jtl